-- MySQL Script generated by MySQL Workbench
-- Sun Oct 30 01:51:44 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema oficina
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `oficina` ;

-- -----------------------------------------------------
-- Schema oficina
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `oficina` DEFAULT CHARACTER SET utf8 ;
USE `oficina` ;

-- -----------------------------------------------------
-- Table `oficina`.`Cliente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `oficina`.`Cliente` ;

CREATE TABLE IF NOT EXISTS `oficina`.`Cliente` (
  `id` INT NOT NULL,
  `Nome` VARCHAR(100) NOT NULL,
  `Telefone` VARCHAR(25) NOT NULL,
  `Email` VARCHAR(150) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `oficina`.`StatusOrdemServico`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `oficina`.`StatusOrdemServico` ;

CREATE TABLE IF NOT EXISTS `oficina`.`StatusOrdemServico` (
  `id` INT NOT NULL,
  `Identificacao` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `oficina`.`OrdemServico`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `oficina`.`OrdemServico` ;

CREATE TABLE IF NOT EXISTS `oficina`.`OrdemServico` (
  `id` INT NOT NULL,
  `idCliente` INT NOT NULL,
  `idStatusOrdemServico` INT NOT NULL,
  `Codigo` VARCHAR(10) NOT NULL,
  `DataEmissao` DATETIME NOT NULL,
  `DataParaConclusao` DATETIME,
  `Valor` DECIMAL(18,2) NOT NULL,
  `DataAutorizacao` DATETIME,
  `Obs` TEXT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `Codigo_UNIQUE` (`Codigo` ASC) VISIBLE,
  INDEX `fk_OrdemServico_StatusOrdemServico_idx` (`idStatusOrdemServico` ASC) VISIBLE,
  INDEX `fk_OrdemServico_Cliente1_idx` (`idCliente` ASC) VISIBLE,
  CONSTRAINT `fk_OrdemServico_StatusOrdemServico`
    FOREIGN KEY (`idStatusOrdemServico`)
    REFERENCES `oficina`.`StatusOrdemServico` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_OrdemServico_Cliente1`
    FOREIGN KEY (`idCliente`)
    REFERENCES `oficina`.`Cliente` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `oficina`.`Marca`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `oficina`.`Marca` ;

CREATE TABLE IF NOT EXISTS `oficina`.`Marca` (
  `id` INT NOT NULL,
  `Identificacao` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `oficina`.`Modelo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `oficina`.`Modelo` ;

CREATE TABLE IF NOT EXISTS `oficina`.`Modelo` (
  `id` INT NOT NULL,
  `idMarca` INT NOT NULL,
  `Identificacao` VARCHAR(45) NOT NULL,
  `Ano` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Veiculo_Marca1_idx` (`idMarca` ASC) VISIBLE,
  CONSTRAINT `fk_Veiculo_Marca1`
    FOREIGN KEY (`idMarca`)
    REFERENCES `oficina`.`Marca` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `oficina`.`Veiculo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `oficina`.`Veiculo` ;

CREATE TABLE IF NOT EXISTS `oficina`.`Veiculo` (
  `id` INT NOT NULL,
  `idOrdemServico` INT NOT NULL,
  `idModelo` INT NOT NULL,
  `Cor` INT NOT NULL,
  `Placa` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Veiculo_Modelo1_idx` (`idModelo` ASC) VISIBLE,
  INDEX `fk_Veiculo_OrdemServico1_idx` (`idOrdemServico` ASC) VISIBLE,
  CONSTRAINT `fk_Veiculo_Modelo1`
    FOREIGN KEY (`idModelo`)
    REFERENCES `oficina`.`Modelo` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Veiculo_OrdemServico1`
    FOREIGN KEY (`idOrdemServico`)
    REFERENCES `oficina`.`OrdemServico` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `oficina`.`Especialidade`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `oficina`.`Especialidade` ;

CREATE TABLE IF NOT EXISTS `oficina`.`Especialidade` (
  `id` INT NOT NULL,
  `Identificacao` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `oficina`.`Equipe`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `oficina`.`Equipe` ;

CREATE TABLE IF NOT EXISTS `oficina`.`Equipe` (
  `id` INT NOT NULL,
  `Identificacao` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `oficina`.`Funcionario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `oficina`.`Funcionario` ;

CREATE TABLE IF NOT EXISTS `oficina`.`Funcionario` (
  `id` INT NOT NULL,
  `idEspecialidade` INT NOT NULL,
  `idEquipe` INT NOT NULL,
  `Codigo` VARCHAR(45) NOT NULL,
  `Nome` VARCHAR(100) NOT NULL,
  `CEP` VARCHAR(10) NOT NULL,
  `Logradouro` VARCHAR(150) NOT NULL,
  `Numero` VARCHAR(10) NOT NULL,
  `Complemento` VARCHAR(10) NULL,
  PRIMARY KEY (`id`, `idEspecialidade`),
  INDEX `fk_Mecanico_Especialidade1_idx` (`idEspecialidade` ASC) VISIBLE,
  INDEX `fk_Mecanico_Equipe1_idx` (`idEquipe` ASC) VISIBLE,
  CONSTRAINT `fk_Mecanico_Especialidade1`
    FOREIGN KEY (`idEspecialidade`)
    REFERENCES `oficina`.`Especialidade` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Mecanico_Equipe1`
    FOREIGN KEY (`idEquipe`)
    REFERENCES `oficina`.`Equipe` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `oficina`.`TabelaServico`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `oficina`.`TabelaServico` ;

CREATE TABLE IF NOT EXISTS `oficina`.`TabelaServico` (
  `id` INT NOT NULL,
  `Identificacao` VARCHAR(100) NOT NULL,
  `ValorTabela` DECIMAL(18,2) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `oficina`.`StatusServico`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `oficina`.`StatusServico` ;

CREATE TABLE IF NOT EXISTS `oficina`.`StatusServico` (
  `id` INT NOT NULL,
  `Identificaca` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `oficina`.`Servico`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `oficina`.`Servico` ;

CREATE TABLE IF NOT EXISTS `oficina`.`Servico` (
  `id` INT NOT NULL,
  `idVeiculo` INT NOT NULL,
  `idTabelaServico` INT NOT NULL,
  `idEquipe` INT NOT NULL,
  `idStatusServico` INT NOT NULL,
  `Descricao` TEXT NOT NULL,
  `ValorPecas` DECIMAL(18,2) NOT NULL,
  `ValorMaoDeObra` DECIMAL(18,2) NOT NULL,
  `DataInicio` DATETIME,
  `DataTermino` DATETIME,
  PRIMARY KEY (`id`),
  INDEX `fk_Servico_Veiculo1_idx` (`idVeiculo` ASC) VISIBLE,
  INDEX `fk_Servico_TabelaServico1_idx` (`idTabelaServico` ASC) VISIBLE,
  INDEX `fk_Servico_Equipe1_idx` (`idEquipe` ASC) VISIBLE,
  INDEX `fk_Servico_StatusServico1_idx` (`idStatusServico` ASC) VISIBLE,
  CONSTRAINT `fk_Servico_Veiculo1`
    FOREIGN KEY (`idVeiculo`)
    REFERENCES `oficina`.`Veiculo` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Servico_TabelaServico1`
    FOREIGN KEY (`idTabelaServico`)
    REFERENCES `oficina`.`TabelaServico` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Servico_Equipe1`
    FOREIGN KEY (`idEquipe`)
    REFERENCES `oficina`.`Equipe` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Servico_StatusServico1`
    FOREIGN KEY (`idStatusServico`)
    REFERENCES `oficina`.`StatusServico` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `oficina`.`Produto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `oficina`.`Produto` ;

CREATE TABLE IF NOT EXISTS `oficina`.`Produto` (
  `id` INT NOT NULL,
  `Identificacao` VARCHAR(45) NOT NULL,
  `ValorReferencia` DECIMAL(18,2) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `oficina`.`Pruduto_ou_servico`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `oficina`.`Pruduto_ou_servico` ;

CREATE TABLE IF NOT EXISTS `oficina`.`Pruduto_ou_servico` (
  `id` INT NOT NULL,
  `idServico` INT NOT NULL,
  `idPeca` INT NOT NULL,
  `ValorPeca` DECIMAL(18,2) NOT NULL,
  PRIMARY KEY (`id`, `idServico`, `idPeca`),
  INDEX `fk_Servico_has_Peca_Peca1_idx` (`idPeca` ASC) VISIBLE,
  INDEX `fk_Servico_has_Peca_Servico1_idx` (`idServico` ASC) VISIBLE,
  CONSTRAINT `fk_Servico_has_Peca_Servico1`
    FOREIGN KEY (`idServico`)
    REFERENCES `oficina`.`Servico` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Servico_has_Peca_Peca1`
    FOREIGN KEY (`idPeca`)
    REFERENCES `oficina`.`Produto` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
